const YourGPT_Config = {	// Thay đổi giá trị cấu hình phù hợp với bạn, Change the config value as appropriate for you
	element: "#YourGPT",
	host: "http://localhost:3000",
	logo: "https://ygpt.onrender.com/logo_icon.png",					
	pattern: "https://ygpt.onrender.com/pattern-dark.png",
	name: "YourGPT Assistant",
	tutorial: "Let ask YourGPT anything...",
	setting_icon: "bi-gear",
	send_icon: "bi-arrow-up-right-circle",
	delete_icon: "bi-trash",
	download_icon: "bi-cloud-download",
	delete_message: "Delete chat",
	download_message: "Download chat",
	download_file: "YourGPT Conversations",
	datetime_format: "HH:mm - DD/MM",
	width: "90%",
	user_text: "light",
	user_color: "#A15BFC",
	user_avatar: "https://github.com/AnLaVN.png",
	title_message: "YourGPT Notification",
	clear_message: "Are you want to clear this chat?",
	error_message: "YourGPT got error, please try later !",
	error_position: "top-0 end-0",
	prompt: "You are 'YourGPT', a friendly chatbot.",
	// firestore_config: {
	//     apiKey: "<API_KEY>",
	//     authDomain: "<PROJECT_ID>.firebaseapp.com",
	//     projectId: "<PROJECT_ID>",
	//     storageBucket: "<PROJECT_ID>.appspot.com",
	//     messagingSenderId: "<MESSAGING_ID>",
	//     appId: "<APP_ID>"
	// },
	// firestore_unique: "UniqueID"
};
YourGPT.loadModule(YourGPT_Config);         // Run YourGPT Client